import { StyleSheet } from "react-native";
import { theme } from "../../constants/theme";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 24,
  },
  container: {
    width: "100%",
    maxWidth: 680,
    alignSelf: "center",
  },
  heroCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: 24,
    borderWidth: 1,
    borderColor: theme.colors.border,
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 2,
  },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: theme.colors.secondary,
    borderRadius: theme.radius.full,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 16,
  },
  badgeText: {
    color: theme.colors.primary,
    fontWeight: "800",
    fontSize: 12,
    letterSpacing: 0.8,
  },
  title: {
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "800",
    color: theme.colors.text,
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: theme.colors.textSoft,
    marginBottom: 18,
  },
  infoRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
    marginBottom: -8,
  },
  infoChip: {
    backgroundColor: "#F7FAF7",
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginHorizontal: 4,
    marginBottom: 8,
  },
  infoChipText: {
    color: theme.colors.text,
    fontWeight: "600",
    fontSize: 13,
  },
  actions: {
    marginTop: 20,
  },
  actionButton: {
    marginBottom: 12,
  },
  selectedCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginTop: 18,
    shadowColor: "#000000",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  selectedEyebrow: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.8,
    color: theme.colors.primary,
    marginBottom: 8,
  },
  selectedTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "800",
    color: theme.colors.text,
    marginBottom: 6,
  },
  selectedSubtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: theme.colors.textSoft,
    marginBottom: 14,
  },
  imageFrame: {
    borderRadius: theme.radius.lg,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: "#EEF4ED",
  },
  // ── Imagen seleccionada: proporción 4:3, sin recorte ─────────────────
  selectedImage: {
    width: "100%",
    aspectRatio: 4 / 3,
  },
  imageMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
    marginTop: 14,
    marginBottom: 6,
  },
  metaChip: {
    backgroundColor: "#F7FAF7",
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginHorizontal: 4,
    marginBottom: 8,
  },
  metaChipText: {
    color: theme.colors.text,
    fontWeight: "600",
    fontSize: 13,
  },
  selectedActions: {
    marginTop: 8,
  },
  analysisLoadingBox: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginTop: 18,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 150,
  },
  analysisLoadingTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: theme.colors.text,
    marginTop: 8,
    marginBottom: 8,
  },
  analysisLoadingText: {
    fontSize: 15,
    lineHeight: 22,
    color: theme.colors.textSoft,
    textAlign: "center",
  },
  saveStatusCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: 18,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginTop: 18,
  },
  saveStatusTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: theme.colors.text,
    marginBottom: 6,
  },
  saveStatusText: {
    fontSize: 14,
    lineHeight: 21,
    color: theme.colors.textSoft,
  },
  saveStatusErrorTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: theme.colors.danger,
    marginBottom: 6,
  },
  footer: {
    marginTop: 18,
    marginBottom: 12,
  },
});

export default styles;